# Generated by Django 5.1.6 on 2025-03-23 12:02

import django.core.validators
import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('branch', models.CharField(choices=[('mechanical', 'Mechanical Engineering'), ('computer_science', 'Computer Science Engineering'), ('civil', 'Civil Engineering'), ('electronics', 'Electronics Engineering'), ('electrical', 'Electrical Engineering')], default='computer_science', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='main_projects', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiniProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('student_1', models.CharField(max_length=100)),
                ('student_2', models.CharField(blank=True, max_length=100, null=True)),
                ('student_3', models.CharField(blank=True, max_length=100, null=True)),
                ('student_4', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('SRS', 'SRS Document'), ('CODE', 'Codebase'), ('DOC', 'Documentation'), ('PPT', 'Presentation'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('file', models.FileField(upload_to=projects.models.ProjectFile.get_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('main_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.mainproject')),
                ('mini_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.miniproject')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('semester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='projects.semester')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('exam_year', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='uploads/questionbank/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.subject')),
            ],
        ),
        migrations.AddField(
            model_name='miniproject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.subject'),
        ),
        migrations.AddField(
            model_name='mainproject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.subject'),
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploads/lecture_notes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'png'])])),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.subject')),
            ],
        ),
    ]
